services:
  openvscode-server:
    image: lscr.io/linuxserver/code-server:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
    volumes:
      - koofr:/docker/vscode/workspace:/workspace
      - koofr:/docker/vscode/config:/config
    networks:
      - o3
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.vscode-r.rule=Host(`vscode.131.186.17.46.nip.io`)
        - traefik.http.routers.vscode-r.entrypoints=websecure
        - traefik.http.routers.vscode-r.tls.certresolver=leresolver
        - traefik.http.routers.vscode-r.service=vscode-s
        - traefik.http.services.vscode-s.loadbalancer.server.port=8443
networks:
  o3:
    external: true
volumes:
  koofr:
    driver: rclone
    driver_opts:
      remote: 'koofr:'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
