services:
  openvscode-server:
    image: gitpod/openvscode-server
    stdin_open: true
    tty: true
    init: true
    user: "0:0"
    volumes:
      - /alist/uos/docker/vscode/data:/home/.openvscode-server:rw
      - /alist/uos/docker/vscode/data/workspaces:/home/workspaces:rw      
    networks:
      - o3
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.vscode-r.rule=Host(`vscode.131.186.17.46.nip.io`)
        - traefik.http.routers.vscode-r.entrypoints=websecure
        - traefik.http.routers.vscode-r.priority=1
        - traefik.http.routers.vscode-r.tls.certresolver=letsencryptresolver
        - traefik.http.routers.vscode-r.service=vscode-s
        - traefik.http.services.vscode-s.loadbalancer.server.port=3000
        - traefik.http.services.vscode-s.loadbalancer.passHostHeader=1
networks:
  o3:
    external: true
