services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - /:/srv
      - filebrowser:/database
      - filebrowser:/config
    networks:
      - o1
    environment:
      - PUID=0
      - PGID=0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == instance1]
      labels:
        - traefik.enable=true
        - traefik.http.routers.filebrowser-r.rule=Host(`file.131.186.17.46.nip.io`)
        - traefik.http.routers.filebrowser-r.entrypoints=websecure
        - traefik.http.routers.filebrowser-r.tls.certresolver=leresolver
        - traefik.http.routers.filebrowser-r.service=filebrowser-s
        - traefik.http.services.filebrowser-s.loadbalancer.server.port=80
networks:
  o1:
    external: true
volumes:
  filebrowser:
    driver: rclone
    driver_opts:
      remote: "alist:uos/docker/filebrowser/data"
      allow_other: "true"
      vfs_cache_mode: writes
      poll_interval: 0
