services:
  openvscode-server:
    image: codercom/code-server:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
    volumes:
      - vscode_config:/config
      - vscode_workspace:/home/coder/.local
    networks:
      - o3
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.vscode-r.rule=Host(`vscode.131.186.17.46.nip.io`)
        - traefik.http.routers.vscode-r.entrypoints=websecure
        - traefik.http.routers.vscode-r.tls.certresolver=leresolver
        - traefik.http.routers.vscode-r.service=vscode-s
        - traefik.http.services.vscode-s.loadbalancer.server.port=8080
networks:
  o3:
    external: true
volumes:
  vscode_config:
    driver: rclone
    driver_opts:
      remote: "alist:uos/docker/vscode/config"
      allow_other: "true"
      vfs_cache_mode: writes
      poll_interval: 0
  vscode_workspace:
    driver: rclone
    driver_opts:
      remote: "alist:uos/docker/vscode/workspace"
      allow_other: "true"
      vfs_cache_mode: writes
      poll_interval: 0


